### ISSUE TITLE
how to auto-generated an class from database?

### ISSUE THREAD

**Issue by weituotian** [rocklau/SqlBuilder#1]
how to auto-generated class

**Comment by rocklau** [comment]
Please check this . https://docs.microsoft.com/en-us/ef/ef6/modeling/designer/workflows/model-first

**Comment by rocklau** [comment]
or this page https://docs.microsoft.com/en-us/ef/ef6/modeling/designer/workflows/database-first

**Comment by weituotian** [comment]
it is great!
